### ISSUE TITLE
Saving a slider position on the crafting window in hideout

### ISSUE THREAD

**Issue by reysonk** [tyfon7/UIFixes#11]
When a flea market search is called from the crafting window, then when it returns, it scrolls up - it's terribly annoying. I would like to fix it by analogy with the inventory slider :)

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/44264ed4-6ec8-447c-91ab-d555c3e6d819)

**Comment by tyfon7** [comment]
Totally get it. 

Fix might be tricky, since the hideout loads the recipes asynchronously. There's no way to immediately be back where you were. Gonna need to think about it.

In the meantime, utilize the searchbar, since UIFixes already remembers the search value and you'll come right back to your search result.

**Comment by tyfon7** [comment]
Fixed in next release
