### ISSUE TITLE
[BUG] Loadout presets UIFixes + SVM

### ISSUE THREAD

**Issue by reysonk** [tyfon7/UIFixes#21]
When [SVM ](https://hub.sp-tarkov.com/files/file/379-server-value-modifier-svm/#comments
)uses the pocket expansion feature and your wonderful mod

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/a95ac624-eee7-45d8-b713-e5dc05d159e6)

If you put bullets that are not there in stash and push "Load Magazine" 

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/71542438-f229-4ecd-91d6-45eb4b6b22f5)

**this message does not appear:**

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/560958e6-a45d-41ec-ba81-cb6a03f07c02)

Plugins and mods list:

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/f17d9847-9828-4cbf-abdd-5b0538ba4df6)
![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/26817ad6-95d4-4bbc-bc14-4a528eebb8ec)

**Comment by reysonk** [comment]
Video DEMO https://drive.google.com/file/d/1WMgAJ8-jma4BXDBFmOP9yLZSrzfJC1PG/view?usp=sharing

**Comment by tyfon7** [comment]
The problem is that the pocket slots added by SVM do not have MongoIDs. UI Fixes makes the preset loader look in your player inventory, not just stash, so it encounters your pockets. The non-mongoID pockets cause it to puke. 

The same thing happens without UI Fixes if you have custom items in your inventory that don't use MongoIDs. 

I would recommend asking GhostFenixx (SVM author) to use proper MongoIDs.
