### ISSUE TITLE
[ Fix request ] Multi-select should work only with topmost container

### ISSUE THREAD

**Issue by 6562680** [tyfon7/UIFixes#64]
Currently i've tried to reorder that 1000 keys (from Tarkov doors) i have and when i've open two backpacks - multiselect is working in both of them same time. Could you reduce region selection only for topmost container?

Also, its strange but BSG `SORTing table` has no button "SORT". Confusing all the times.

**Comment by tyfon7** [comment]
It's actually non-trivial to figure out what the "top" window is, there isn't actually a concept of focus. Plus I think there are valid scenarios to keep it working this way.

The code does prevent items "behind" other windows from being selected, so you shouldn't be having trouble with unintentional selection. If the issue is getting only the items you want in the selection box, don't forget you can hold shift and draw more selection boxes to add to the selection.
