### ISSUE TITLE
[ Fix Request ] Holding shift prevents to start running of an actor

### ISSUE THREAD

**Issue by 6562680** [tyfon7/UIFixes#79]
Finally i found WHY its happened in Buyanov's game.

Steps:
1. Set in options RMB CLICK to `start aiming` (not HOLD to `aiming`), set in options SHIFT HOLD to `run`
2. Start to AIM somewhere
3. Click RMB to stop aiming
4. Hold shift to Run
5. All is working correctly, person start to run

Steps to catch the bug:
1. ~ Same
2. ~ Same
3. Press Q/E while aiming to lean to the side
4. Click RMB to stop aiming
5. Hold shift to Run
6. [ Bug ] WHILE animation of "leaning back" is playing - actor is ignore Shift to Run need to wait until animation ends then Hold again

[ Same note is sent to BSG Support ]

**Comment by tyfon7** [comment]
This is due to how animations work in tarkov - there's state machines for every animation and whether you can transition from a given state to any other state depends on there being specific code written to handle it. Specifically for sprinting, it's not checking all the time if shift is down (like some other games), but rather when you start moving, if sprinting is a valid thing to do *at that time*, and it isn't in a lot of cases. While standing up, while coming back from aiming, etc. 

It's really tricky code to mess with, so for the time being I'm not going there.
